// Auto-generated from registers.yaml - DO NOT EDIT
// Generated by: bin/generate_registers
//
// This file contains register offset constants, field enums, and field tables
// for the ATI Rage 128 Pro graphics controller.
//
// Field values are PRE-SHIFTED and can be ORed directly into register values.
// Example: reg |= GMC_BRUSH_DATATYPE_SOLIDCOLOR | GMC_ROP3_SRCCOPY;

#ifndef ATI_REGS_GEN_H
#define ATI_REGS_GEN_H

#include <stdint.h>
#include <stddef.h>

// Named value entry for multi-bit fields
typedef struct {
    const char *name;
    uint32_t value;  // raw, unshifted value
} field_value_t;

// Field entry structure for REPL field display
typedef struct {
    const char *name;
    uint8_t shift;
    uint8_t width;
    const field_value_t *values;  // NULL if no named values
} field_entry_t;


// ============================================================================
// Field Constants
// ============================================================================

// CRTC_GEN_CNTL fields
enum {
    CRTC_DBL_SCAN_EN = (1u << 0),
    CRTC_INTERLACE_EN = (1u << 1),
    CRTC_C_SYNC_EN = (1u << 4),
    CRTC_PIX_WIDTH_SHIFT = 8,
    CRTC_PIX_WIDTH_MASK = 0x700u,
    CRTC_PIX_WIDTH_4BPP = 0x100u,
    CRTC_PIX_WIDTH_8BPP = 0x200u,
    CRTC_PIX_WIDTH_15BPP = 0x300u,
    CRTC_PIX_WIDTH_16BPP = 0x400u,
    CRTC_PIX_WIDTH_24BPP = 0x500u,
    CRTC_PIX_WIDTH_32BPP = 0x600u,
    CRTC_CUR_EN = (1u << 16),
    CRTC_CUR_MODE_SHIFT = 17,
    CRTC_CUR_MODE_MASK = 0xe0000u,
    CRTC_CUR_MODE_64X64_MONO = 0u,
    CRTC_EXT_DISP_EN = (1u << 24),
    CRTC_EN = (1u << 25),
    CRTC_DISP_REQ_EN_B = (1u << 26),
};

// CRTC_EXT_CNTL fields
enum {
    CRTC_VGA_XOVERSCAN = (1u << 0),
    VGA_BLINK_RATE_SHIFT = 1,
    VGA_BLINK_RATE_MASK = 0x6u,
    VGA_ATI_LINEAR = (1u << 3),
    VGA_128KAP_PAGING = (1u << 4),
    VGA_TEXT_132 = (1u << 5),
    VGA_XCRT_CNT_EN = (1u << 6),
    CRTC_HSYNC_DIS = (1u << 8),
    CRTC_VSYNC_DIS = (1u << 9),
    CRTC_DISPLAY_DIS = (1u << 10),
    CRTC_SYNC_TRISTATE = (1u << 11),
    CRTC_HSYNC_TRISTATE = (1u << 12),
    CRTC_VSYNC_TRISTATE = (1u << 13),
    CRTC_CRT_ON = (1u << 15),
    VGA_CUR_B_TEST = (1u << 17),
    VGA_PACK_DIS = (1u << 18),
    VGA_MEM_PS_EN = (1u << 19),
    VGA_READ_PREFETCH_DIS = (1u << 20),
    DFIFO_EXTSENSE = (1u << 21),
    FP_OUT_EN = (1u << 22),
    FP_ACTIVE = (1u << 23),
    VCRTC_IDX_MASTER_SHIFT = 24,
    VCRTC_IDX_MASTER_MASK = 0x7f000000u,
};

// CRTC_H_TOTAL_DISP fields
enum {
    CRTC_H_TOTAL_SHIFT = 0,
    CRTC_H_TOTAL_MASK = 0x1ffu,
    CRTC_H_DISP_SHIFT = 16,
    CRTC_H_DISP_MASK = 0xff0000u,
};

// CRTC_H_SYNC_STRT_WID fields
enum {
    CRTC_H_SYNC_STRT_PIX_SHIFT = 0,
    CRTC_H_SYNC_STRT_PIX_MASK = 0x7u,
    CRTC_H_SYNC_STRT_CHAR_SHIFT = 3,
    CRTC_H_SYNC_STRT_CHAR_MASK = 0xff8u,
    CRTC_H_SYNC_WID_SHIFT = 16,
    CRTC_H_SYNC_WID_MASK = 0x3f0000u,
    CRTC_H_SYNC_POL = (1u << 23),
};

// CRTC_V_TOTAL_DISP fields
enum {
    CRTC_V_TOTAL_SHIFT = 0,
    CRTC_V_TOTAL_MASK = 0x7ffu,
    CRTC_V_DISP_SHIFT = 16,
    CRTC_V_DISP_MASK = 0x7ff0000u,
};

// CRTC_V_SYNC_STRT_WID fields
enum {
    CRTC_V_SYNC_STRT_SHIFT = 0,
    CRTC_V_SYNC_STRT_MASK = 0x7ffu,
    CRTC_V_SYNC_WID_SHIFT = 16,
    CRTC_V_SYNC_WID_MASK = 0x1f0000u,
    CRTC_V_SYNC_POL = (1u << 23),
};

// DAC_CNTL fields
enum {
    DAC_RANGE_CNTL_SHIFT = 0,
    DAC_RANGE_CNTL_MASK = 0x3u,
    DAC_BLANKING = (1u << 2),
    DAC_CMP_EN = (1u << 3),
    DAC_CMP_OUTPUT = (1u << 7),
    DAC_8BIT_EN = (1u << 8),
    DAC_4BPP_PIX_ORDER = (1u << 9),
    DAC_TVO_EN = (1u << 10),
    DAC_TVO_OVR_EXCL = (1u << 11),
    DAC_TVO_16BPP_DITH_EN = (1u << 12),
    DAC_VGA_ADR_EN = (1u << 13),
    DAC_PDWN = (1u << 15),
    DAC_CRC_EN = (1u << 19),
    DAC_MASK_SHIFT = 24,
    DAC_MASK_MASK = 0xff000000u,
};

// GEN_RESET_CNTL fields
enum {
    SOFT_RESET_GUI = (1u << 0),
};

// PC_NGUI_CTLSTAT fields
enum {
    PC_FLUSH_ALL_SHIFT = 0,
    PC_FLUSH_ALL_MASK = 0xffu,
    PC_BUSY = (1u << 31),
};

// GEN_INT_CNTL fields
enum {
    CRTC_VBLANK_INT_EN = (1u << 0),
    CRTC_VLINE_INT_EN = (1u << 1),
    CRTC_VSYNC_INT_EN = (1u << 2),
    SNAPSHOT_INT_EN = (1u << 3),
    FP_DETECT_INT_EN = (1u << 10),
    BUSMASTER_EOL_INT_EN = (1u << 16),
    I2C_INT_EN = (1u << 17),
    MPP_GP_INT_EN = (1u << 18),
    GUI_IDLE_INT_EN = (1u << 19),
    VIPH_INT_EN = (1u << 24),
};

// PM4_BUFFER_CNTL fields
enum {
    PM4_BUFFER_CNTL_NOUPDATE = (1u << 27),
    PM4_BUFFER_MODE_SHIFT = 28,
    PM4_BUFFER_MODE_MASK = 0xf0000000u,
    PM4_BUFFER_MODE_NONPM4 = 0u,
    PM4_BUFFER_MODE_192PIO = 0x10000000u,
    PM4_BUFFER_MODE_192BM = 0x20000000u,
    PM4_BUFFER_MODE_128PIO_64INDBM = 0x30000000u,
    PM4_BUFFER_MODE_128BM_64INDBM = 0x40000000u,
    PM4_BUFFER_MODE_64PIO_128INDBM = 0x50000000u,
    PM4_BUFFER_MODE_64BM_128INDBM = 0x60000000u,
    PM4_BUFFER_MODE_64PIO_64VCBM_64INDBM = 0x70000000u,
    PM4_BUFFER_MODE_64BM_64VCBM_64INDBM = 0x80000000u,
    PM4_BUFFER_MODE_64PIO_64VCPIO_64INDPIO = 0xf0000000u,
};

// PM4_MICRO_CNTL fields
enum {
    PM4_MICRO_FREERUN = (1u << 30),
};

// PM4_STAT fields
enum {
    PM4_FIFOCNT_SHIFT = 0,
    PM4_FIFOCNT_MASK = 0xfffu,
};

// GUI_STAT fields
enum {
    GUI_FIFO_CNT_SHIFT = 0,
    GUI_FIFO_CNT_MASK = 0xfffu,
    PM4_BUSY = (1u << 16),
    MICRO_BUSY = (1u << 17),
    FPU_BUSY = (1u << 18),
    VC_BUSY = (1u << 19),
    IDCT_BUSY = (1u << 20),
    ENG_EV_BUSY = (1u << 21),
    SETUP_BUSY = (1u << 22),
    EDGEWALK_BUSY = (1u << 23),
    ADDRESSING_BUSY = (1u << 24),
    ENG_3D_BUSY = (1u << 25),
    ENG_2D_SM_BUSY = (1u << 26),
    ENG_2D_BUSY = (1u << 27),
    GUI_WB_BUSY = (1u << 28),
    CACHE_BUSY = (1u << 29),
    GUI_ACTIVE = (1u << 31),
};

// DP_GUI_MASTER_CNTL fields
enum {
    GMC_SRC_PITCH_OFFSET_CNTL = (1u << 0),
    GMC_DST_PITCH_OFFSET_CNTL = (1u << 1),
    GMC_SRC_CLIPPING = (1u << 2),
    GMC_DST_CLIPPING = (1u << 3),
    GMC_BRUSH_DATATYPE_SHIFT = 4,
    GMC_BRUSH_DATATYPE_MASK = 0xf0u,
    GMC_BRUSH_DATATYPE_8X8_MONO = 0u,
    GMC_BRUSH_DATATYPE_8X8_MONO_TRANS = 0x10u,
    GMC_BRUSH_DATATYPE_8X1_MONO = 0x20u,
    GMC_BRUSH_DATATYPE_8X1_MONO_TRANS = 0x30u,
    GMC_BRUSH_DATATYPE_1X8_MONO = 0x40u,
    GMC_BRUSH_DATATYPE_1X8_MONO_TRANS = 0x50u,
    GMC_BRUSH_DATATYPE_32X1_MONO = 0x60u,
    GMC_BRUSH_DATATYPE_32X1_MONO_TRANS = 0x70u,
    GMC_BRUSH_DATATYPE_32X32_MONO = 0x80u,
    GMC_BRUSH_DATATYPE_32X32_MONO_TRANS = 0x90u,
    GMC_BRUSH_DATATYPE_8X8_COLOR = 0xa0u,
    GMC_BRUSH_DATATYPE_8X1_COLOR = 0xb0u,
    GMC_BRUSH_DATATYPE_1X8_COLOR = 0xc0u,
    GMC_BRUSH_DATATYPE_SOLIDCOLOR = 0xd0u,
    GMC_BRUSH_DATATYPE_NONE = 0xf0u,
    GMC_DST_DATATYPE_SHIFT = 8,
    GMC_DST_DATATYPE_MASK = 0xf00u,
    GMC_DST_DATATYPE_PSEUDO_COLOR_8 = 0x200u,
    GMC_DST_DATATYPE_ARGB_1555 = 0x300u,
    GMC_DST_DATATYPE_RGB_565 = 0x400u,
    GMC_DST_DATATYPE_RGB_888 = 0x500u,
    GMC_DST_DATATYPE_ARGB_8888 = 0x600u,
    GMC_DST_DATATYPE_RGB_332 = 0x700u,
    GMC_DST_DATATYPE_Y8_GREYSCALE = 0x800u,
    GMC_DST_DATATYPE_RGB_8_GREYSCALE = 0x900u,
    GMC_DST_DATATYPE_YUV_422_VYUY = 0xb00u,
    GMC_DST_DATATYPE_YUV_422_YVYU = 0xc00u,
    GMC_DST_DATATYPE_AYUV_444_8888 = 0xe00u,
    GMC_DST_DATATYPE_ARGB_4444 = 0xf00u,
    GMC_SRC_DATATYPE_SHIFT = 12,
    GMC_SRC_DATATYPE_MASK = 0x3000u,
    GMC_SRC_DATATYPE_MONO = 0u,
    GMC_SRC_DATATYPE_MONO_TRANS = 0x1000u,
    GMC_SRC_DATATYPE_DST_COLOR = 0x3000u,
    GMC_BYTE_PIX_ORDER = (1u << 14),
    GMC_CONVERSION_TEMP = (1u << 15),
    GMC_ROP3_SHIFT = 16,
    GMC_ROP3_MASK = 0xff0000u,
    GMC_ROP3_SRCCOPY = 0xcc0000u,
    GMC_SRC_SOURCE_SHIFT = 24,
    GMC_SRC_SOURCE_MASK = 0x7000000u,
    GMC_SRC_SOURCE_MEMORY = 0x2000000u,
    GMC_SRC_SOURCE_HOST_DATA = 0x3000000u,
    GMC_SRC_SOURCE_HOST_DATA_ALIGNED = 0x4000000u,
    GMC_3D_FCN_EN = (1u << 27),
    GMC_CLR_CMP_CNTL_DIS = (1u << 28),
    GMC_AUX_CLIP_DIS = (1u << 29),
    GMC_WR_MSK_DIS = (1u << 30),
    GMC_LD_BRUSH_Y_X = (1u << 31),
};

// DP_DATATYPE fields
enum {
    HOST_BIG_ENDIAN_EN = (1u << 29),
};

// DP_CNTL fields
enum {
    DST_X_LEFT_TO_RIGHT = (1u << 0),
    DST_Y_TOP_TO_BOTTOM = (1u << 1),
    DST_Y_MAJOR = (1u << 2),
};

// DEFAULT_SC_BOTTOM_RIGHT fields
enum {
    DEFAULT_SC_RIGHT_SHIFT = 0,
    DEFAULT_SC_RIGHT_MASK = 0x3fffu,
    DEFAULT_SC_BOTTOM_SHIFT = 16,
    DEFAULT_SC_BOTTOM_MASK = 0x3fff0000u,
};

// DEFAULT_OFFSET fields
enum {
    DEFAULT_OFFSET_SHIFT = 0,
    DEFAULT_OFFSET_MASK = 0x3ffffffu,
};

// DEFAULT_PITCH fields
enum {
    DEFAULT_PITCH_SHIFT = 0,
    DEFAULT_PITCH_MASK = 0x3ffu,
    DEFAULT_TILE = (1u << 16),
};

// ============================================================================
// Field Value Tables (for REPL display of named values)
// ============================================================================

static const field_value_t crtc_pix_width_values[] = {
    {"4BPP", 1},
    {"8BPP", 2},
    {"15BPP", 3},
    {"16BPP", 4},
    {"24BPP", 5},
    {"32BPP", 6},
    {NULL, 0}
};

static const field_value_t crtc_cur_mode_values[] = {
    {"64X64_MONO", 0},
    {NULL, 0}
};

static const field_value_t pm4_buffer_mode_values[] = {
    {"NONPM4", 0},
    {"192PIO", 1},
    {"192BM", 2},
    {"128PIO_64INDBM", 3},
    {"128BM_64INDBM", 4},
    {"64PIO_128INDBM", 5},
    {"64BM_128INDBM", 6},
    {"64PIO_64VCBM_64INDBM", 7},
    {"64BM_64VCBM_64INDBM", 8},
    {"64PIO_64VCPIO_64INDPIO", 15},
    {NULL, 0}
};

static const field_value_t gmc_brush_datatype_values[] = {
    {"8X8_MONO", 0},
    {"8X8_MONO_TRANS", 1},
    {"8X1_MONO", 2},
    {"8X1_MONO_TRANS", 3},
    {"1X8_MONO", 4},
    {"1X8_MONO_TRANS", 5},
    {"32X1_MONO", 6},
    {"32X1_MONO_TRANS", 7},
    {"32X32_MONO", 8},
    {"32X32_MONO_TRANS", 9},
    {"8X8_COLOR", 10},
    {"8X1_COLOR", 11},
    {"1X8_COLOR", 12},
    {"SOLIDCOLOR", 13},
    {"NONE", 15},
    {NULL, 0}
};

static const field_value_t gmc_dst_datatype_values[] = {
    {"PSEUDO_COLOR_8", 2},
    {"ARGB_1555", 3},
    {"RGB_565", 4},
    {"RGB_888", 5},
    {"ARGB_8888", 6},
    {"RGB_332", 7},
    {"Y8_GREYSCALE", 8},
    {"RGB_8_GREYSCALE", 9},
    {"YUV_422_VYUY", 11},
    {"YUV_422_YVYU", 12},
    {"AYUV_444_8888", 14},
    {"ARGB_4444", 15},
    {NULL, 0}
};

static const field_value_t gmc_src_datatype_values[] = {
    {"MONO", 0},
    {"MONO_TRANS", 1},
    {"DST_COLOR", 3},
    {NULL, 0}
};

static const field_value_t gmc_rop3_values[] = {
    {"SRCCOPY", 204},
    {NULL, 0}
};

static const field_value_t gmc_src_source_values[] = {
    {"MEMORY", 2},
    {"HOST_DATA", 3},
    {"HOST_DATA_ALIGNED", 4},
    {NULL, 0}
};

// ============================================================================
// Field Tables (for REPL display)
// ============================================================================

static const field_entry_t crtc_gen_cntl_fields[] = {
    {"CRTC_DBL_SCAN_EN", 0, 1, NULL},
    {"CRTC_INTERLACE_EN", 1, 1, NULL},
    {"CRTC_C_SYNC_EN", 4, 1, NULL},
    {"CRTC_PIX_WIDTH", 8, 3, crtc_pix_width_values},
    {"CRTC_CUR_EN", 16, 1, NULL},
    {"CRTC_CUR_MODE", 17, 3, crtc_cur_mode_values},
    {"CRTC_EXT_DISP_EN", 24, 1, NULL},
    {"CRTC_EN", 25, 1, NULL},
    {"CRTC_DISP_REQ_EN_B", 26, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t crtc_ext_cntl_fields[] = {
    {"CRTC_VGA_XOVERSCAN", 0, 1, NULL},
    {"VGA_BLINK_RATE", 1, 2, NULL},
    {"VGA_ATI_LINEAR", 3, 1, NULL},
    {"VGA_128KAP_PAGING", 4, 1, NULL},
    {"VGA_TEXT_132", 5, 1, NULL},
    {"VGA_XCRT_CNT_EN", 6, 1, NULL},
    {"CRTC_HSYNC_DIS", 8, 1, NULL},
    {"CRTC_VSYNC_DIS", 9, 1, NULL},
    {"CRTC_DISPLAY_DIS", 10, 1, NULL},
    {"CRTC_SYNC_TRISTATE", 11, 1, NULL},
    {"CRTC_HSYNC_TRISTATE", 12, 1, NULL},
    {"CRTC_VSYNC_TRISTATE", 13, 1, NULL},
    {"CRTC_CRT_ON", 15, 1, NULL},
    {"VGA_CUR_B_TEST", 17, 1, NULL},
    {"VGA_PACK_DIS", 18, 1, NULL},
    {"VGA_MEM_PS_EN", 19, 1, NULL},
    {"VGA_READ_PREFETCH_DIS", 20, 1, NULL},
    {"DFIFO_EXTSENSE", 21, 1, NULL},
    {"FP_OUT_EN", 22, 1, NULL},
    {"FP_ACTIVE", 23, 1, NULL},
    {"VCRTC_IDX_MASTER", 24, 7, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t crtc_h_total_disp_fields[] = {
    {"CRTC_H_TOTAL", 0, 9, NULL},
    {"CRTC_H_DISP", 16, 8, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t crtc_h_sync_strt_wid_fields[] = {
    {"CRTC_H_SYNC_STRT_PIX", 0, 3, NULL},
    {"CRTC_H_SYNC_STRT_CHAR", 3, 9, NULL},
    {"CRTC_H_SYNC_WID", 16, 6, NULL},
    {"CRTC_H_SYNC_POL", 23, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t crtc_v_total_disp_fields[] = {
    {"CRTC_V_TOTAL", 0, 11, NULL},
    {"CRTC_V_DISP", 16, 11, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t crtc_v_sync_strt_wid_fields[] = {
    {"CRTC_V_SYNC_STRT", 0, 11, NULL},
    {"CRTC_V_SYNC_WID", 16, 5, NULL},
    {"CRTC_V_SYNC_POL", 23, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t dac_cntl_fields[] = {
    {"DAC_RANGE_CNTL", 0, 2, NULL},
    {"DAC_BLANKING", 2, 1, NULL},
    {"DAC_CMP_EN", 3, 1, NULL},
    {"DAC_CMP_OUTPUT", 7, 1, NULL},
    {"DAC_8BIT_EN", 8, 1, NULL},
    {"DAC_4BPP_PIX_ORDER", 9, 1, NULL},
    {"DAC_TVO_EN", 10, 1, NULL},
    {"DAC_TVO_OVR_EXCL", 11, 1, NULL},
    {"DAC_TVO_16BPP_DITH_EN", 12, 1, NULL},
    {"DAC_VGA_ADR_EN", 13, 1, NULL},
    {"DAC_PDWN", 15, 1, NULL},
    {"DAC_CRC_EN", 19, 1, NULL},
    {"DAC_MASK", 24, 8, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t gen_reset_cntl_fields[] = {
    {"SOFT_RESET_GUI", 0, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t pc_ngui_ctlstat_fields[] = {
    {"PC_FLUSH_ALL", 0, 8, NULL},
    {"PC_BUSY", 31, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t gen_int_cntl_fields[] = {
    {"CRTC_VBLANK_INT_EN", 0, 1, NULL},
    {"CRTC_VLINE_INT_EN", 1, 1, NULL},
    {"CRTC_VSYNC_INT_EN", 2, 1, NULL},
    {"SNAPSHOT_INT_EN", 3, 1, NULL},
    {"FP_DETECT_INT_EN", 10, 1, NULL},
    {"BUSMASTER_EOL_INT_EN", 16, 1, NULL},
    {"I2C_INT_EN", 17, 1, NULL},
    {"MPP_GP_INT_EN", 18, 1, NULL},
    {"GUI_IDLE_INT_EN", 19, 1, NULL},
    {"VIPH_INT_EN", 24, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t pm4_buffer_cntl_fields[] = {
    {"PM4_BUFFER_CNTL_NOUPDATE", 27, 1, NULL},
    {"PM4_BUFFER_MODE", 28, 4, pm4_buffer_mode_values},
    {NULL, 0, 0, NULL}
};

static const field_entry_t pm4_micro_cntl_fields[] = {
    {"PM4_MICRO_FREERUN", 30, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t pm4_stat_fields[] = {
    {"PM4_FIFOCNT", 0, 12, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t gui_stat_fields[] = {
    {"GUI_FIFO_CNT", 0, 12, NULL},
    {"PM4_BUSY", 16, 1, NULL},
    {"MICRO_BUSY", 17, 1, NULL},
    {"FPU_BUSY", 18, 1, NULL},
    {"VC_BUSY", 19, 1, NULL},
    {"IDCT_BUSY", 20, 1, NULL},
    {"ENG_EV_BUSY", 21, 1, NULL},
    {"SETUP_BUSY", 22, 1, NULL},
    {"EDGEWALK_BUSY", 23, 1, NULL},
    {"ADDRESSING_BUSY", 24, 1, NULL},
    {"ENG_3D_BUSY", 25, 1, NULL},
    {"ENG_2D_SM_BUSY", 26, 1, NULL},
    {"ENG_2D_BUSY", 27, 1, NULL},
    {"GUI_WB_BUSY", 28, 1, NULL},
    {"CACHE_BUSY", 29, 1, NULL},
    {"GUI_ACTIVE", 31, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t dp_gui_master_cntl_fields[] = {
    {"GMC_SRC_PITCH_OFFSET_CNTL", 0, 1, NULL},
    {"GMC_DST_PITCH_OFFSET_CNTL", 1, 1, NULL},
    {"GMC_SRC_CLIPPING", 2, 1, NULL},
    {"GMC_DST_CLIPPING", 3, 1, NULL},
    {"GMC_BRUSH_DATATYPE", 4, 4, gmc_brush_datatype_values},
    {"GMC_DST_DATATYPE", 8, 4, gmc_dst_datatype_values},
    {"GMC_SRC_DATATYPE", 12, 2, gmc_src_datatype_values},
    {"GMC_BYTE_PIX_ORDER", 14, 1, NULL},
    {"GMC_CONVERSION_TEMP", 15, 1, NULL},
    {"GMC_ROP3", 16, 8, gmc_rop3_values},
    {"GMC_SRC_SOURCE", 24, 3, gmc_src_source_values},
    {"GMC_3D_FCN_EN", 27, 1, NULL},
    {"GMC_CLR_CMP_CNTL_DIS", 28, 1, NULL},
    {"GMC_AUX_CLIP_DIS", 29, 1, NULL},
    {"GMC_WR_MSK_DIS", 30, 1, NULL},
    {"GMC_LD_BRUSH_Y_X", 31, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t dp_datatype_fields[] = {
    {"HOST_BIG_ENDIAN_EN", 29, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t dp_cntl_fields[] = {
    {"DST_X_LEFT_TO_RIGHT", 0, 1, NULL},
    {"DST_Y_TOP_TO_BOTTOM", 1, 1, NULL},
    {"DST_Y_MAJOR", 2, 1, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t default_sc_bottom_right_fields[] = {
    {"DEFAULT_SC_RIGHT", 0, 14, NULL},
    {"DEFAULT_SC_BOTTOM", 16, 14, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t default_offset_fields[] = {
    {"DEFAULT_OFFSET", 0, 26, NULL},
    {NULL, 0, 0, NULL}
};

static const field_entry_t default_pitch_fields[] = {
    {"DEFAULT_PITCH", 0, 10, NULL},
    {"DEFAULT_TILE", 16, 1, NULL},
    {NULL, 0, 0, NULL}
};

// ============================================================================
// Register Offsets
// ============================================================================

enum {
    CRTC_GEN_CNTL = 0x50,
    CRTC_EXT_CNTL = 0x54,
    CRTC_H_TOTAL_DISP = 0x200,
    CRTC_H_SYNC_STRT_WID = 0x204,
    CRTC_V_TOTAL_DISP = 0x208,
    CRTC_V_SYNC_STRT_WID = 0x20c,
    CRTC_OFFSET = 0x224,
    CRTC_OFFSET_CNTL = 0x228,
    CRTC_PITCH = 0x22c,
    DAC_CNTL = 0x58,
    PALETTE_INDEX = 0xb0,
    PALETTE_DATA = 0xb4,
    GEN_RESET_CNTL = 0xf0,
    PC_NGUI_CTLSTAT = 0x184,
    GEN_INT_CNTL = 0x40,
    DDA_CONFIG = 0x2e0,
    DDA_ON_OFF = 0x2e4,
    OVR_CLR = 0x230,
    OVR_WID_LEFT_RIGHT = 0x234,
    OVR_WID_TOP_BOTTOM = 0x238,
    OV0_SCALE_CNTL = 0x420,
    MPP_TB_CONFIG = 0x1c0,
    MPP_GP_CONFIG = 0x1c8,
    SUBPIC_CNTL = 0x540,
    VIPH_CONTROL = 0x1d0,
    I2C_CNTL_1 = 0x94,
    CAP0_TRIG_CNTL = 0x950,
    CAP1_TRIG_CNTL = 0x9c0,
    PM4_BUFFER_OFFSET = 0x700,
    PM4_BUFFER_CNTL = 0x704,
    PM4_BUFFER_WM_CNTL = 0x708,
    PM4_BUFFER_DL_RPTR_ADDR = 0x70c,
    PM4_BUFFER_DL_RPTR = 0x710,
    PM4_BUFFER_DL_WPTR = 0x714,
    PM4_BUFFER_DL_WPTR_DELAY = 0x718,
    PM4_BUFFER_ADDR = 0x7f0,
    PM4_MICRO_CNTL = 0x7fc,
    PM4_FIFO_DATA_EVEN = 0x1000,
    PM4_FIFO_DATA_ODD = 0x1004,
    PM4_MICROCODE_ADDR = 0x7d4,
    PM4_MICROCODE_RADDR = 0x7d8,
    PM4_MICROCODE_DATAH = 0x7dc,
    PM4_MICROCODE_DATAL = 0x7e0,
    PM4_STAT = 0x7b8,
    GUI_STAT = 0x1740,
    DP_GUI_MASTER_CNTL = 0x146c,
    DP_DATATYPE = 0x16c4,
    DP_MIX = 0x16c8,
    DP_WRITE_MSK = 0x16cc,
    DP_CNTL = 0x16c0,
    DP_BRUSH_BKGD_CLR = 0x15dc,
    DP_BRUSH_FRGD_CLR = 0x1578,
    DP_SRC_BKGD_CLR = 0x15dc,
    DP_SRC_FRGD_CLR = 0x15d8,
    GUI_SCRATCH_REG0 = 0x15e0,
    GUI_SCRATCH_REG1 = 0x15e4,
    GUI_SCRATCH_REG2 = 0x15e8,
    GUI_SCRATCH_REG3 = 0x15ec,
    GUI_SCRATCH_REG4 = 0x15f0,
    GUI_SCRATCH_REG5 = 0x15f4,
    SC_LEFT = 0x1640,
    SC_TOP = 0x1648,
    SC_RIGHT = 0x1644,
    SC_BOTTOM = 0x164c,
    SC_TOP_LEFT = 0x16ec,
    SC_BOTTOM_RIGHT = 0x16f0,
    SRC_SC_BOTTOM = 0x165c,
    SRC_SC_RIGHT = 0x1654,
    SRC_SC_BOTTOM_RIGHT = 0x16f4,
    DEFAULT_SC_BOTTOM_RIGHT = 0x16e8,
    AUX_SC_CNTL = 0x1660,
    DST_OFFSET = 0x1404,
    DST_PITCH = 0x1408,
    DST_X = 0x141c,
    DST_Y = 0x1420,
    DST_X_Y = 0x1594,
    DST_Y_X = 0x1438,
    DST_WIDTH = 0x140c,
    DST_HEIGHT = 0x1410,
    DST_WIDTH_HEIGHT = 0x1598,
    DST_BRES_ERR = 0x1628,
    DST_BRES_INC = 0x162c,
    DST_BRES_DEC = 0x1630,
    SRC_OFFSET = 0x15ac,
    SRC_PITCH = 0x15b0,
    SRC_X = 0x141c,
    SRC_Y = 0x1420,
    SRC_X_Y = 0x1590,
    SRC_Y_X = 0x1434,
    DEFAULT_OFFSET = 0x16e0,
    DEFAULT_PITCH = 0x16e4,
    HOST_DATA0 = 0x17c0,
    HOST_DATA1 = 0x17c4,
    HOST_DATA2 = 0x17c8,
    HOST_DATA3 = 0x17cc,
    HOST_DATA4 = 0x17d0,
    HOST_DATA5 = 0x17d4,
    HOST_DATA6 = 0x17d8,
    HOST_DATA7 = 0x17dc,
    HOST_DATA_LAST = 0x17e0,
    SCALE_3D_CNTL = 0x1a00,
};

// ============================================================================
// ATI_REGISTERS X-macro
// Used to generate read/write functions, register tables, etc.
// X(func_name, const_name, offset, mode, fields)
// ============================================================================

#define ATI_REGISTERS \
  X(crtc_gen_cntl, CRTC_GEN_CNTL, 0x50, RW, crtc_gen_cntl_fields) \
  X(crtc_ext_cntl, CRTC_EXT_CNTL, 0x54, RW, crtc_ext_cntl_fields) \
  X(crtc_h_total_disp, CRTC_H_TOTAL_DISP, 0x200, RW, crtc_h_total_disp_fields) \
  X(crtc_h_sync_strt_wid, CRTC_H_SYNC_STRT_WID, 0x204, RW, crtc_h_sync_strt_wid_fields) \
  X(crtc_v_total_disp, CRTC_V_TOTAL_DISP, 0x208, RW, crtc_v_total_disp_fields) \
  X(crtc_v_sync_strt_wid, CRTC_V_SYNC_STRT_WID, 0x20c, RW, crtc_v_sync_strt_wid_fields) \
  X(crtc_offset, CRTC_OFFSET, 0x224, RW, NULL) \
  X(crtc_offset_cntl, CRTC_OFFSET_CNTL, 0x228, RW, NULL) \
  X(crtc_pitch, CRTC_PITCH, 0x22c, RW, NULL) \
  X(dac_cntl, DAC_CNTL, 0x58, RW, dac_cntl_fields) \
  X(palette_index, PALETTE_INDEX, 0xb0, RW, NULL) \
  X(palette_data, PALETTE_DATA, 0xb4, RW, NULL) \
  X(gen_reset_cntl, GEN_RESET_CNTL, 0xf0, RW, gen_reset_cntl_fields) \
  X(pc_ngui_ctlstat, PC_NGUI_CTLSTAT, 0x184, RW, pc_ngui_ctlstat_fields) \
  X(gen_int_cntl, GEN_INT_CNTL, 0x40, RW, gen_int_cntl_fields) \
  X(dda_config, DDA_CONFIG, 0x2e0, RW, NULL) \
  X(dda_on_off, DDA_ON_OFF, 0x2e4, RW, NULL) \
  X(ovr_clr, OVR_CLR, 0x230, RW, NULL) \
  X(ovr_wid_left_right, OVR_WID_LEFT_RIGHT, 0x234, RW, NULL) \
  X(ovr_wid_top_bottom, OVR_WID_TOP_BOTTOM, 0x238, RW, NULL) \
  X(ov0_scale_cntl, OV0_SCALE_CNTL, 0x420, RW, NULL) \
  X(mpp_tb_config, MPP_TB_CONFIG, 0x1c0, RW, NULL) \
  X(mpp_gp_config, MPP_GP_CONFIG, 0x1c8, RW, NULL) \
  X(subpic_cntl, SUBPIC_CNTL, 0x540, RW, NULL) \
  X(viph_control, VIPH_CONTROL, 0x1d0, RW, NULL) \
  X(i2c_cntl_1, I2C_CNTL_1, 0x94, RW, NULL) \
  X(cap0_trig_cntl, CAP0_TRIG_CNTL, 0x950, RW, NULL) \
  X(cap1_trig_cntl, CAP1_TRIG_CNTL, 0x9c0, RW, NULL) \
  X(pm4_buffer_offset, PM4_BUFFER_OFFSET, 0x700, RW, NULL) \
  X(pm4_buffer_cntl, PM4_BUFFER_CNTL, 0x704, RW, pm4_buffer_cntl_fields) \
  X(pm4_buffer_wm_cntl, PM4_BUFFER_WM_CNTL, 0x708, RW, NULL) \
  X(pm4_buffer_dl_rptr_addr, PM4_BUFFER_DL_RPTR_ADDR, 0x70c, RW, NULL) \
  X(pm4_buffer_dl_rptr, PM4_BUFFER_DL_RPTR, 0x710, RW, NULL) \
  X(pm4_buffer_dl_wptr, PM4_BUFFER_DL_WPTR, 0x714, RW, NULL) \
  X(pm4_buffer_dl_wptr_delay, PM4_BUFFER_DL_WPTR_DELAY, 0x718, RW, NULL) \
  X(pm4_buffer_addr, PM4_BUFFER_ADDR, 0x7f0, RW, NULL) \
  X(pm4_micro_cntl, PM4_MICRO_CNTL, 0x7fc, RW, pm4_micro_cntl_fields) \
  X(pm4_fifo_data_even, PM4_FIFO_DATA_EVEN, 0x1000, WO, NULL) \
  X(pm4_fifo_data_odd, PM4_FIFO_DATA_ODD, 0x1004, WO, NULL) \
  X(pm4_microcode_addr, PM4_MICROCODE_ADDR, 0x7d4, RW, NULL) \
  X(pm4_microcode_raddr, PM4_MICROCODE_RADDR, 0x7d8, RW, NULL) \
  X(pm4_microcode_datah, PM4_MICROCODE_DATAH, 0x7dc, RW, NULL) \
  X(pm4_microcode_datal, PM4_MICROCODE_DATAL, 0x7e0, RW, NULL) \
  X(pm4_stat, PM4_STAT, 0x7b8, RO, pm4_stat_fields) \
  X(gui_stat, GUI_STAT, 0x1740, RO, gui_stat_fields) \
  X(dp_gui_master_cntl, DP_GUI_MASTER_CNTL, 0x146c, RW, dp_gui_master_cntl_fields) \
  X(dp_datatype, DP_DATATYPE, 0x16c4, RW, dp_datatype_fields) \
  X(dp_mix, DP_MIX, 0x16c8, RW, NULL) \
  X(dp_write_msk, DP_WRITE_MSK, 0x16cc, RW, NULL) \
  X(dp_cntl, DP_CNTL, 0x16c0, RW, dp_cntl_fields) \
  X(dp_brush_bkgd_clr, DP_BRUSH_BKGD_CLR, 0x15dc, RW, NULL) \
  X(dp_brush_frgd_clr, DP_BRUSH_FRGD_CLR, 0x1578, RW, NULL) \
  X(dp_src_bkgd_clr, DP_SRC_BKGD_CLR, 0x15dc, RW, NULL) \
  X(dp_src_frgd_clr, DP_SRC_FRGD_CLR, 0x15d8, RW, NULL) \
  X(gui_scratch_reg0, GUI_SCRATCH_REG0, 0x15e0, RW, NULL) \
  X(gui_scratch_reg1, GUI_SCRATCH_REG1, 0x15e4, RW, NULL) \
  X(gui_scratch_reg2, GUI_SCRATCH_REG2, 0x15e8, RW, NULL) \
  X(gui_scratch_reg3, GUI_SCRATCH_REG3, 0x15ec, RW, NULL) \
  X(gui_scratch_reg4, GUI_SCRATCH_REG4, 0x15f0, RW, NULL) \
  X(gui_scratch_reg5, GUI_SCRATCH_REG5, 0x15f4, RW, NULL) \
  X(sc_left, SC_LEFT, 0x1640, RW, NULL) \
  X(sc_top, SC_TOP, 0x1648, RW, NULL) \
  X(sc_right, SC_RIGHT, 0x1644, RW, NULL) \
  X(sc_bottom, SC_BOTTOM, 0x164c, RW, NULL) \
  X(sc_top_left, SC_TOP_LEFT, 0x16ec, RW, NULL) \
  X(sc_bottom_right, SC_BOTTOM_RIGHT, 0x16f0, RW, NULL) \
  X(src_sc_bottom, SRC_SC_BOTTOM, 0x165c, RW, NULL) \
  X(src_sc_right, SRC_SC_RIGHT, 0x1654, RW, NULL) \
  X(src_sc_bottom_right, SRC_SC_BOTTOM_RIGHT, 0x16f4, RW, NULL) \
  X(default_sc_bottom_right, DEFAULT_SC_BOTTOM_RIGHT, 0x16e8, RW, default_sc_bottom_right_fields) \
  X(aux_sc_cntl, AUX_SC_CNTL, 0x1660, RW, NULL) \
  X(dst_offset, DST_OFFSET, 0x1404, RW, NULL) \
  X(dst_pitch, DST_PITCH, 0x1408, RW, NULL) \
  X(dst_x, DST_X, 0x141c, RW, NULL) \
  X(dst_y, DST_Y, 0x1420, RW, NULL) \
  X(dst_x_y, DST_X_Y, 0x1594, WO, NULL) \
  X(dst_y_x, DST_Y_X, 0x1438, WO, NULL) \
  X(dst_width, DST_WIDTH, 0x140c, RW, NULL) \
  X(dst_height, DST_HEIGHT, 0x1410, RW, NULL) \
  X(dst_width_height, DST_WIDTH_HEIGHT, 0x1598, RW, NULL) \
  X(dst_bres_err, DST_BRES_ERR, 0x1628, RW, NULL) \
  X(dst_bres_inc, DST_BRES_INC, 0x162c, RW, NULL) \
  X(dst_bres_dec, DST_BRES_DEC, 0x1630, RW, NULL) \
  X(src_offset, SRC_OFFSET, 0x15ac, RW, NULL) \
  X(src_pitch, SRC_PITCH, 0x15b0, RW, NULL) \
  X(src_x, SRC_X, 0x141c, RW, NULL) \
  X(src_y, SRC_Y, 0x1420, RW, NULL) \
  X(src_x_y, SRC_X_Y, 0x1590, WO, NULL) \
  X(src_y_x, SRC_Y_X, 0x1434, WO, NULL) \
  X(default_offset, DEFAULT_OFFSET, 0x16e0, RW, default_offset_fields) \
  X(default_pitch, DEFAULT_PITCH, 0x16e4, RW, default_pitch_fields) \
  X(host_data0, HOST_DATA0, 0x17c0, WO, NULL) \
  X(host_data1, HOST_DATA1, 0x17c4, WO, NULL) \
  X(host_data2, HOST_DATA2, 0x17c8, WO, NULL) \
  X(host_data3, HOST_DATA3, 0x17cc, WO, NULL) \
  X(host_data4, HOST_DATA4, 0x17d0, WO, NULL) \
  X(host_data5, HOST_DATA5, 0x17d4, WO, NULL) \
  X(host_data6, HOST_DATA6, 0x17d8, WO, NULL) \
  X(host_data7, HOST_DATA7, 0x17dc, WO, NULL) \
  X(host_data_last, HOST_DATA_LAST, 0x17e0, WO, NULL) \
  X(scale_3d_cntl, SCALE_3D_CNTL, 0x1a00, RW, NULL)

#endif // ATI_REGS_GEN_H