// Auto-generated from registers/r128.yaml - DO NOT EDIT
// Generated by: bin/generate_registers --chip r128 --prefix R128_
//
// ATI Rage 128 Pro specific register definitions.
//
// Field values are PRE-SHIFTED and can be ORed directly into register values.
// Example: reg |= R128_GMC_BRUSH_DATATYPE_SOLIDCOLOR | R128_GMC_ROP3_SRCCOPY;

#ifndef R128_REGS_GEN_H
#define R128_REGS_GEN_H

#include <stdint.h>
#include <stddef.h>


// Note: field_value_t, field_entry_t, and flag enums are defined in common_regs_gen.h

#include "common_regs_gen.h"


// No registers defined for r128

#define R128_REGISTERS /* empty */


#endif // R128_REGS_GEN_H
