// Auto-generated from registers/r100.yaml - DO NOT EDIT
// Generated by: bin/generate_registers --chip r100 --prefix R100_
//
// ATI Radeon R100 (Mobility M6) specific register definitions.
//
// Field values are PRE-SHIFTED and can be ORed directly into register values.
// Example: reg |= R100_GMC_BRUSH_DATATYPE_SOLIDCOLOR | R100_GMC_ROP3_SRCCOPY;

#ifndef R100_REGS_GEN_H
#define R100_REGS_GEN_H

#include <stdint.h>
#include <stddef.h>


// Note: field_value_t, field_entry_t, and flag enums are defined in common_regs_gen.h

#include "common_regs_gen.h"


// No registers defined for r100

#define R100_REGISTERS /* empty */


#endif // R100_REGS_GEN_H
